# Generated by Django 5.0.3 on 2024-03-16 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('price', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(max_length=200)),
                ('full_title', models.TextField()),
                ('size', models.CharField(blank=True, max_length=100, null=True)),
                ('bedrooms', models.IntegerField(blank=True, null=True)),
                ('floor', models.IntegerField(blank=True, null=True)),
                ('image_urls', models.TextField(blank=True, null=True)),
                ('url', models.URLField(null=True, unique=True)),
            ],
        ),
    ]
