# Generated by Django 5.0.3 on 2024-03-16 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parserss', '0002_alter_listing_address_alter_listing_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='address',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='size',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='title',
            field=models.CharField(max_length=1000),
        ),
    ]
