# Generated by Django 5.0.3 on 2024-03-16 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parserss', '0003_alter_listing_address_alter_listing_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='url',
            field=models.URLField(max_length=500, null=True, unique=True),
        ),
    ]
