# Generated by Django 5.0.3 on 2024-03-18 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parserss', '0004_alter_listing_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='floor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
